### ISSUE TITLE
lib.pipe shows wrong documentation

### ISSUE THREAD

**Issue by katexochen** [nix-community/noogle#144]
**What happened**

entry for `lib.pipe` shows documentation of `lib.lists.unique`

**Steps to Reproduce**

https://noogle.dev/f/lib/pipe

**Screenshots**

![image](https://github.com/nix-community/noogle/assets/49727155/5688b46a-0b69-4a55-b877-631cbebe2283)

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: x86_64-linux
 - Browser chrome
 - Version 122.0.6261.111

**Comment by hsjobeki** [comment]
Thanks for the report. Wondering why this happens. We recently migrated `lib.trivial` to use doc-comments (rfc145) I'll look into it.
Alias beeing detected wrong as well. `lib.trivial.pipe` documentation is fine though.
