### ISSUE TITLE
Update UI when navigating browser history

### ISSUE THREAD

**Issue by asymmetric** [nix-community/noogle#19]
**Is your feature request related to a problem? Please describe.**

1. visit https://noogle.dev/?selected=%22lib.sources.cleanSourceWith%22&term=%22cleansourcewith%22
2. visit https://noogle.dev/?selected=%22builtins.baseNameOf%22&term=%22basenameof%22
3. hit back in the browser history
4. the UI is not updated

**Describe the solution you'd like**
I would like to be brought back to the previously selected entry.

**Additional context**
Tested in both FF and Chrome.

**Comment by hsjobeki** [comment]
Resolved with the latest Release. New UI New bugs :)
