### ISSUE TITLE
Add mkOverride mkDefault etc.

### ISSUE THREAD

**Issue by nikstur** [nix-community/noogle#20]
mkOverride, mkDefault etc. from https://github.com/NixOS/nixpkgs/blob/master/lib/modules.nix are missing in Noogle. It would be nice to see them too.

**Comment by hsjobeki** [comment]
Are discovered now:
https://noogle.dev/f/lib/mkDefault
https://noogle.dev/f/lib/mkOverride
(and much more ;)
