### ISSUE TITLE
mem leak on main page?

### ISSUE THREAD

**Issue by KiaraGrouwstra** [nix-community/noogle#213]
**What happened**
just opening noogle's main page, the tab (as per `about:processes`) seems to already take multiple gb of ram for me.
might there be something up with js on the page?

**Steps to Reproduce**
1. Go to https://noogle.dev
2. Open `about:processes`
3. Find multiple gb of memory used

**Expected behavior**
no mem leak

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - Screen resolution (optional)

or 

**Smartphone (please complete the following information):**
 - Device: lenovo ideapad
 - OS: nixos
 - Browser firefox
 - Version 126.0

**Comment by hsjobeki** [comment]
Tried with both firefox and chrome. In both cases the memory usage was around 40-50k which is quite low.

![grafik](https://github.com/nix-community/noogle/assets/50398876/03b83ce3-1f5c-41a3-97a0-79158a8df155)

I know this sucks, but if you really ran into this problem can you try the following steps:

Open a "pivate window" and make sure no browser extensions are allowed to run. To avoid any side effects.

Then open the task manager about:processes and attach a screenshot of the usage and the exact url / steps / clicks you performed on the site ?

**Comment by KiaraGrouwstra** [comment]
thanks. i disabled plugins in firefox's incognito mode. it seems it's still taking dozens of mb ram, but that's looking not much different from other pages i'm seeing.
i guess i'll close this then.

![image](https://github.com/nix-community/noogle/assets/3059397/a12217a9-1bbd-40c3-8ad8-94898bde9520)

**Comment by KiaraGrouwstra** [comment]
tried a bit more, looks like my main issue here was caused by firefox extension darkreader.
