### ISSUE TITLE
Why is lib.elem signature missing?

### ISSUE THREAD

**Issue by doronbehar** [nix-community/noogle#227]
I'd expect it to have the signature:

```
elem :: e -> [l] -> bool
```

Is this due to missing docs in Nix?

**Comment by hsjobeki** [comment]
To understand why the function signature is missing: 
`lib.elem` and `lib.lists.elem` are basically aliases which point to `builtins.elem`
https://github.com/NixOS/nixpkgs/blob/master/lib/default.nix#L68

liib.elem doesn't have any implementation in nixpkgs. And also doesnt have any doc-comment that would carry the type information.

Thank you for discovering the issue. I think it is worth fixing the issue 

I'll fix this by forwarding the type of the underlying implementation (builtins.elem -> lib.elem) which makes sense for all functions that are undocumented and aliases of other documented functions.
