### ISSUE TITLE
Missing lib.types

### ISSUE THREAD

**Issue by Kranzes** [nix-community/noogle#23]

**Comment by hsjobeki** [comment]
@Kranzes Unfortunately, the lib.types file doesn't offer any doc-comments. Thus it is almost impossible for noogle to guess what attributes actually matter. 

If you'd like to see more automatic discovery from noogle in nixpkgs, we need consistent markers/doc-strings 

https://github.com/NixOS/rfcs/pull/145

**Comment by hsjobeki** [comment]
Done; all lib.types **functions** are discovered.
see https://noogle.dev/q?term=types

Somebody still needs to write more documentation.

Please let me know if a type is missing.
