### ISSUE TITLE
Opening the home page in a 3rd Noogle tab flickers theme

### ISSUE THREAD

**Issue by imatpot** [nix-community/noogle#233]
**What happened**

If you have 2 Noogle tabs open and open a third Noogle home page specifically, the theme in all Noogle tabs starts acting up and all interactions become unusably laggy.

This doesn't happen if you open any other page though. Only the landing page!

**Steps to Reproduce**

1. Go to [noogle.dev](https://noogle.dev/)
1. In a second tab, also go to [noogle.dev](https://noogle.dev/)
1. In a third tab, also go to [noogle.dev](https://noogle.dev/)
1. Enjoy the disco 🕺

**Expected behavior**

I don't expect it to do anything weird in the third tab, especially not across all Noogle tabs.

**Desktop**

 - OS: macOS 14.5 & NixOS Stable 24.05
 - Browser: Firefox
 - Version: Latest(?)
 - Screen resolution: Any

**Comment by hsjobeki** [comment]
Hey thanks for the issue.
Unfortunately i cannot reproduce it. I used firefox version 126.0.1 (64-Bit).
Do you use any darkreader or other extensions that may create those side effects?

If you encounter issues with it, and its comming from some extension please let me know. I'll hapily debug this.

**Comment by imatpot** [comment]
I'm using the latest Firefox version, 126.0.1 on my M1 MacBook and the 64-bit version on NixOS. The issue persists even in troubleshoot mode (all extensions disabled), although it only seems to be consistent with 4 tabs in that case.

It doesn't appear to be an issue in Chrome 125.0.6422.142 however.

**Comment by 21CSM** [comment]
I am able to recreate this bug on both MacOS (Ventura) and Ubuntu (22.04) on both Firefox (127.0.2 64-bit) and Safari (17.5).

It seems to be repeatable when one has their system settings default to "dark mode" and navigates between directories i.e ```/f``` to ```/md```. 
I was not able to recreate with my system settings as "light mode". I don't have any browser extensions installed.

I would love to help, but I am having difficulties developing the website code on my local machine using direnv. I am not too clear on how to get it running. Any assistance would be great - would love to contribute here.

**WARNING:** Flashing lights.

https://github.com/nix-community/noogle/assets/81891917/4f14b3da-d28c-43af-8686-d884d6ed7d9a

**Comment by hsjobeki** [comment]
Thanks with that i was able to reproduce the issue. I will try to fix this asap.

**Comment by bew** [comment]
Not sure if it's directly related, I don't always get as much flash but on 3rd tab after a refresh on the homepage it starts flashing a little, but more importantly it uses 100%+ of CPU and fills RAM little by little (few gigs in less than a minute..).
![Peek 2024-10-23 00-27](https://github.com/user-attachments/assets/bba56b24-e9a5-4782-8355-14c7cfeb7d93)

**Comment by hsjobeki** [comment]
> Not sure if it's directly related, I don't always get as much flash but on 3rd tab after a refresh on the homepage it starts flashing a little, but more importantly it uses 100%+ of CPU and fills RAM little by little (few gigs in less than a minute..).
> 
> On NixOS, with Firefox v123
> 
> ![Peek 2024-10-23 00-27](https://github.com/user-attachments/assets/bba56b24-e9a5-4782-8355-14c7cfeb7d93)
> 

I now changed the theme behavior and planning to debug further once i got some spare time.

Could you test again with the latest deployment?

**Comment by hsjobeki** [comment]
Please continue discussion in #414 

I'd like to collect all potentially relevant memory issues in one place.
