### ISSUE TITLE
document fetch*

### ISSUE THREAD

**Issue by wmertens** [nix-community/noogle#25]
the fetch functions are in pkgs, not lib, and they're a bit mysterious :-)

**Comment by hsjobeki** [comment]
Good Idea!.

Just for reference if i come back to that later.
https://github.com/NixOS/nixpkgs/blob/master/pkgs/top-level/all-packages.nix#L971
Inline-documentation should be where the function was declared (in fetchgithub/default.nix)

Problematic is finding the right name.
function actual name: `pkgs.fetchFromGitHub`
function defined in: `build-support/fetchgithub/default.nix`
but renamed during export in `pkgs/top-level/all-packages.nix`

Maybe I should look into https://github.com/mlvzk/manix how they find the scopes.

**Comment by hsjobeki** [comment]
The fetchers are discovered now. If you know how they work, please consider making a PR in nixkgs to add doc-comments.
https://noogle.dev/f/pkgs/fetchFromGitHub
(Noogle tells you the source location)
