### ISSUE TITLE
Standartization of output marker for Example section

### ISSUE THREAD

**Issue by ony** [nix-community/noogle#31]
**Is your feature request related to a problem? Please describe.**
It is not clear what is format to distinguish part of Nix expression and output of evaluation. See question in  https://github.com/NixOS/nixpkgs/pull/225496#discussion_r1174612310

From [`lib.attrsets.foldAttrs`](https://noogle.dev/?selected=%22lib.attrsets.foldAttrs%22&term=%22lib.attrsets.foldAttrs%22):
> Example
> ```
> foldAttrs (item: acc: [item] ++ acc) [] [{ a = 2; } { a = 3; }]
> => { a = [ 2 3 ]; }
> ```

From [`lib.attrsets.foldlAttrs`](https://noogle.dev/?selected=%22lib.attrsets.foldlAttrs%22&term=%22lib.attrsets.foldlAttrs%22)
> Example
> ```
> foldlAttrs
>   (acc: name: value: {
>     sum = acc.sum + value;
>     names = acc.names ++ [name];
>   })
>   { sum = 0; names = []; }
>   {
>     foo = 1;
>     bar = 10;
>   }
> ->
>   {
>     sum = 11;
>     names = ["bar" "foo"];
>   }
> 
> foldlAttrs
>   (throw "function not needed")
>   123
>   {};
> ->
>   123
> ```

Notice that in first example it is `=>` (looks like double line arrow pointing to right) that separates expression to run from expected output. While second one uses `->` (looks like single line arrow to right).

**Describe the solution you'd like**
Before growing coverage of comment-based documentation it worth to agree on some format.

I have nothing specific, but something popular might be more preferred. E.g. `>>> ` prefix for what needs to be evaluated as  Nix expression.

E.g. [Haddoc/doctest uses prefix](https://github.com/sol/doctest#a-basic-example)
>
> ```haskell
> -- | Compute Fibonacci numbers
> --
> -- Examples:
> --
> -- >>> fib 10
> -- 55
> ```

Same in [Python doctest](https://realpython.com/python-doctest/#writing-your-own-doctest-tests-in-python)
> ```python
>  """Compute and return the sum of two numbers.
> 
>  Usage examples:
>  >>> add(4.0, 2.0)
>  6.0
>  >>> add(4, 2)
>  6.0
>  """
> ```

**Comment by hsjobeki** [comment]
Excellent idea... We need a standard for many things in the comments.
If you're interested, I opened an RFC for the doc-comments in general -> https://github.com/NixOS/rfcs/pull/145.

I'm looking forward that laying the foundation for further enhancements and rich features within doc-comments.
But before we can specify rich features we need to specify what a doc-comment is.

Currently, I expect the comments to be refactored to be doc-comments. From there, I think of something like [tesh](https://github.com/OceanSprint/tesh) to test the examples in nixpkgs, which would be nice.

Once the format of doc-comments is specified, we can move forward to identify more rich features, such as examples that can be tested and types that everyone can use. So if you feel capable of it, you could write an RFC for that (based on RFC145, of course)

Unfortunately, Noogle cannot just change how nixpkgs currently is. If you want my opinion there:
`->` is already a valid nix-token `TOKEN_IMPLICATION`. It could feel natural to use it here, although it is not used like that in Nix.

Suppose you want to test examples in your nix-codebase right away. You can fork the noogle/indexer (which outputs JSON) and feed it into something like Tesh (mentioned above).

**Comment by hsjobeki** [comment]
Not planned. Noogle (for now) focuses only on documentation discovery. ;)
