### ISSUE TITLE
Include links to `NixOS` or `nixpkgs` manuals

### ISSUE THREAD

**Issue by MattSturgeon** [nix-community/noogle#328]
**Is your feature request related to a problem? Please describe.**
Some functions in nixpkgs mention where they are documented in the reference manual(s), often instead of having a proper doc-comment.

**Describe the solution you'd like**
Scan comments located before attributes for references to the manual docs.

- A reference should match the pattern `\bdoc/.*\.md\b`.
- A link should match `\bhttps://nixos\.org/manual/.*\b`.

If links or src refs are found, include a link to the manual in Noogle.

**Describe alternatives you've considered**
Scan for doc references, and include the relevant section of the docs verbatim in Noogle instead of a link.

**Additional context**

For example, [`pkgs.writeScript`](https://noogle.dev/f/pkgs/writeScript)

<img width="500" alt="Screenshot_20240906-174305.png" src="https://github.com/user-attachments/assets/2d1eb265-834c-4063-ae65-e9813eeb4a18">

```nix
  # See doc/build-helpers/trivial-build-helpers.chapter.md
  # or https://nixos.org/manual/nixpkgs/unstable/#trivial-builder-text-writing
  writeScript = name: text: writeTextFile { inherit name text; executable = true; };
```

**Comment by hsjobeki** [comment]
The better solution would be to move the reference documentation. Back into the code.
Further tutorials should stay in /doc folder.

The `:doc` function in the nix-repl should also print the documentation now if one exists.
So we shouldn't really adding new features to the tooling.

**Comment by MattSturgeon** [comment]
You've closed this as "completed" but I don't see any changes pushed. Your comment makes me wonder if you intended to close this as "not planed"?

**Comment by hsjobeki** [comment]
Yeah i wanted to close this as not planned. :smile: Just didn't see the button, or missclicked

**Comment by MattSturgeon** [comment]
Sure thing. Thanks for clarifying, and thanks for considering the issue to begin with :grin:

**Comment by hsjobeki** [comment]
I now implemented https://github.com/nix-community/noogle/pull/348 which should display the links.

**Comment by MattSturgeon** [comment]
Awesome, thanks. Looking at https://1d0e7891.noogle.pages.dev/f/pkgs/writeScript, it seems the comment line gets rendered verbatim?

So in most instances we end up with `"or https://nixos.org/manual/...."`.

I think this adequately solves the issue, although it could be potentially ugly or confusing when a comment line that includes a link also includes unrelated text out of context.

I'm guessing a solution is more effort than it's worth though.

**Comment by hsjobeki** [comment]
> Awesome, thanks. Looking at https://1d0e7891.noogle.pages.dev/f/pkgs/writeScript, it seems the comment line gets rendered verbatim?
> 
> So in most instances we end up with `"or https://nixos.org/manual/...."`.
> 
> I think this adequately solves the issue, although it could be potentially ugly or confusing when a comment line that includes a link also includes unrelated text out of context.
> 
> I'm guessing a solution is more effort than it's worth though.

Yes. I'll need to implement mulitline joining the single line comments then. I'll maybe do it later.
