### ISSUE TITLE
Is there a url param to query a search?

### ISSUE THREAD

**Issue by starptr** [nix-community/noogle#362]
**Is your feature request related to a problem? Please describe.**
Is it possible to query the search through a url parameter? This will allow browsers to use the custom search feature with Noogle.

**Describe the solution you'd like**
An endpoint, eg. `https://noogle.dev/?query=my_search_string`, so that browsers can use this for a custom search.

**Describe alternatives you've considered**
None

**Additional context**
Please let me know if this is already possible; I couldn't find a documentation about it if so.

**Comment by DaRacci** [comment]
there is a search url, my firefox template is as follows: https://noogle.dev/q?term={searchTerms}

**Comment by hsjobeki** [comment]
See @DaRacci s answer. There are the following  query options:

route: `/q`

queries: `term` `from` `to` `page` `limit`
