### ISSUE TITLE
Display function definitions

### ISSUE THREAD

**Issue by h7x4** [nix-community/noogle#371]
Noogle is really great for looking up documentation for a function, and I use it almost daily. But I still find myself having to move back to the nix code to see how a function is implemented from time to time.

Would it be possible to extract entire function definitions from the nix code, and display them on the web page?

Furthermore, it would be really neat if the code could be analyzed and hyperlinked, so that clicking on a function in the code would take you to it's own noogle page (although, this could be a separate issue to be implemented later)

Not sure how much work this is, and whether the project has a detailed enough nix parser to support it. Feel free to close if it's way out of scope. I'd be happy to help out as well, if I'm able to get a bit of onboarding.

This might be related to #352

**Comment by hsjobeki** [comment]
Great Idea should be absolutely possible. Thanks for providing the Idea. I'll hapily add it
