### ISSUE TITLE
Builtin functions have invalid source code links

### ISSUE THREAD

**Issue by MattSturgeon** [nix-community/noogle#50]
**What happened**
Clicking a "browse source code" link on a builtin function's documentation opens an invalid link in the [nixpkgs repo](https://github.com/NixOS/nixpkgs).

**Steps to Reproduce**
1. Go to a builtin function's [documentation](https://noogle.dev/?selected=%22builtins.elem%22&term=%22builtins.elem%22).
2. Click on "Browse source code".
3. Note that the [opened page](https://github.com/NixOS/nixpkgs/blob/master/builtins) does not exist.

**Expected behavior**
Either
- No link should be shown in the documentation
- The link should open the C++ code implementing the builtin
- The link should open the nix code where the builtin is stubbed & documented

<details>
<summary><strong>Screenshots</strong></summary>

![image](https://github.com/nix-community/noogle/assets/5046562/93bc1592-5632-4bfa-abca-c7886e67bba5)
![image](https://github.com/nix-community/noogle/assets/5046562/fe407c88-7d4b-4575-a0b0-3f3f4b99d0c9)

</details>

**Comment by hsjobeki** [comment]
Thx for the report i'll fix the bug. I cannot link to the source location currently for builtins.

**Comment by hsjobeki** [comment]
Resolved. See https://noogle.dev/q?term=builtins
