### ISSUE TITLE
term argument in URL ignored if not surrounded by %22

### ISSUE THREAD

**Issue by jezcope** [nix-community/noogle#51]
**What happened**
I tried to set up a shortcut to prompt for text and then open the URL `https://noogle.dev/?term=<text I entered>` but found it didn't work as expected. By trial and error, I found I needed to surround the search text with URL-encoded double quotes `%22` to make it work.

**Steps to Reproduce**
1. Enter <https://noogle.dev/?term=getattrs> in browser location bar and press enter
2. Noogle loads with empty search box and no results, the same as simply opening <https://noogle.dev>
3. Enter <https://noogle.dev/?term=%22getattrs%22> in browser location bar and press enter
4. Noogle correctly shows search results for `getattrs`

**Expected behavior**
Noogle should perform the search given in the URL in both cases.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Chromium
 - Version 118

**Comment by hsjobeki** [comment]
Yes, that's how noogle knows your parameter is a string. 
Wondering: if you have to type `%22`, my browser (chrome as well) works with just putting regular `"` I don't have to encode anything. 
Note if you integrate some tooling check out how the filter argument works.

**Comment by hsjobeki** [comment]
Thanks for the report though. Just discovered another bug by playing with some arguments.

**Comment by hsjobeki** [comment]
Resolved with the latest release
