### ISSUE TITLE
404 for builtin.fetchurl

### ISSUE THREAD

**Issue by Korny666** [nix-community/noogle#57]
**What happened**
https://noogle.dev/?term=%22fetchurl%22 source code link returns 404 

**Steps to Reproduce**
1. Go to https://noogle.dev/?term=%22fetchurl%22
2. Click on https://github.com/NixOS/nixpkgs/blob/master/builtins
3. 404

**Expected behavior**
No or Correct link

**Screenshots**

**Desktop (please complete the following information):**
 - OS: NixOS
 - Chromium

I want to help to fix this but I need a pointer where to look at first.

**Comment by hsjobeki** [comment]
Resolved. See: https://noogle.dev/f/builtins/fetchurl.
