### ISSUE TITLE
autofocus input on landing page

### ISSUE THREAD

**Issue by asymmetric** [nix-community/noogle#59]
**Is your feature request related to a problem? Please describe.**
When visiting noogle.dev, I'd like the main search input to be autofocused, so I can start searching immediately.

**Describe the solution you'd like**
Use the [`autofocus`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autofocus) HTML attribute.

**Describe alternatives you've considered**
Leave as is, which is still fine.

**Additional context**
None.

**Comment by hsjobeki** [comment]
Fixed by #60. Thanks for the report @asymmetric  :heart:
