### ISSUE TITLE
Changing to front page or function flashes website

### ISSUE THREAD

**Issue by SuperSandro2000** [nix-community/noogle#62]
**What happened**
Navigating to the front page or pkgs.fetchFromGitHub flashes website.

**Steps to Reproduce**

See video

**Expected behavior**
Background should stay in the theme color.

**Screenshots**

https://github.com/nix-community/noogle/assets/7258858/4744b99a-1b34-490f-9b09-552731bde263

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 120.0.6099.200

**Comment by hsjobeki** [comment]
Thanks for the report. I investigated why this happened.

Problem is that the website is loaded before the theme gets loaded.
There is https://mui.com/material-ui/experimental-api/css-theme-variables/overview/ 
to fix this, but it didn't work when i tried it last time.
