### ISSUE TITLE
deprecated notice

### ISSUE THREAD

**Issue by mightyiam** [nix-community/noogle#64]
I'd love deprecated items to show up as such. For example, It seems that [this one](https://noogle.dev/f/lib/mapAttrsFlatten) is deprecated, because the source file it's implemented in is `lib/deprecated.nix`.

**Comment by hsjobeki** [comment]
I don't make any predictions based on file names. 
I think a valid solution for this is to do the following:

```nix

  /**
   # Deprecated
   
   This function is deprecated!  Use xy instead.
 
   # Usage 
   
   calls a function (f attr value ) for each record item. returns a list.
   
   */
  mapAttrsFlatten = f: r: map (attr: f attr r.${attr}) (attrNames r);
```

As of RFC145 markdown is totally valid and will be rendered with noogle.
